/**:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: false
    
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
                   
    odom1: /odometry/gps
    odom1_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]