ekf_local2: # it has continous state estimation
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: false
    publish_tf: true # publish the transform from map to base_link, so we can visualize it in rviz and use it for navigation
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    odom0: /odom
    #X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X¨,Y¨,Z¨
    odom0_config: [true, true, false,
                  false, false, true,
                  true,  true,  false,
                  false, false, true,
                  false, false, false]


    imu0: /imu/data
    imu0_config: [false, false, false,
                  false,  false,  false,
                  false, false, false,
                  false,  false,  true,
                  true,  true,  false]
              
    imu0_differential: false        
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: false


    process_noise_covariance: [
      0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01
    ]
    

ekf_filter_node_gps_enc:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true 
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map

    initial_state: [1.0, 1.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
                   
    odom1: /odometry/gps
    odom1_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    process_noise_covariance: [
          0.00016, 0.0,     0.0, 0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # x
          0.0,     0.00041, 0.0, 0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # y
          0.0,     0.0,     1e-6, 0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # z
          0.0,     0.0,     0.0,  1e-6, 0.0,  0.0,     0.0,    0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # roll
          0.0,     0.0,     0.0,  0.0,  1e-6, 0.0,     0.0,    0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # pitch
          0.0,     0.0,     0.0,  0.0,  0.0,  0.00003, 0.0,    0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # yaw
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0001, 0.0,      0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # x_dot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.000051, 0.0, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # y_dot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      1e-6, 0.0,  0.0,  0.0, 0.0,    0.0,    0.0, # z_dot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 1e-6,  0.0,  0.0, 0.0,    0.0,    0.0, # roll_dot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,   1e-6, 0.0, 0.0,    0.0,    0.0, # pitch_dot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,   0.0,  1e-6, 0.0,    0.0,    0.0, # yaw_dot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,   0.0,  0.0, 0.0002, 0.0,    0.0, # x_ddot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,   0.0,  0.0, 0.0,    0.0014, 0.0, # y_ddot
          0.0,     0.0,     0.0,  0.0,  0.0,  0.0,     0.0,    0.0,      0.0, 0.0,   0.0,  0.0, 0.0,    0.0,    1e-6  # z_ddot
        ]

navsat_transform2:
  ros__parameters:
      frequency: 30.0
      delay: 5.0
      magnetic_declination_radians: 0.0  # For lat/long 55.944831, -3.186998
      yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
      zero_altitude: false
      broadcast_utm_transform: true
      publish_filtered_gps: true
      use_odometry_yaw: true
      wait_for_datum: false

